version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "7432:7432"
    environment:
      - TZ=Europe/Moscow
      - UID=100001
      - GID=100001
    volumes:
      - ./config.json:/app/config.json
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7432"]
      interval: 30s
      retries: 3
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge